"use client";

import { Shield, Target, Bookmark, Activity, ArrowRight } from "lucide-react";
import { cn } from "@/lib/utils";
import { SectionHeader } from "../home/SectionHeader";

const services = [
  {
    icon: Shield,
    title: "NABL Accredited Laboratories",
    description: "National Accreditation Board for Testing and Calibration Laboratories (NABL) is India's highest accreditation body for testing laboratories.",
    whyRequired: "Testing in a NABL-accredited laboratory means your reports are generated using internationally recognized quality systems, validated analytical methods, and competent technical personnel.",
    color: "from-emerald-400 to-teal-500",
    bg: "bg-emerald-50/50",
    hover: "hover:border-emerald-200",
    tag: "Accreditation"
  },
  {
    icon: Target,
    title: "FSSAI Recognized Laboratories",
    description: "These laboratories are notified or recognized by the Food Safety and Standards Authority of India to perform food analysis in accordance with the Food Safety and Standards Act and its regulations.",
    whyRequired: "Reports generated by recognized laboratories are accepted for many regulatory submissions and support compliance with Indian food safety requirements.",
    color: "from-blue-400 to-indigo-500",
    bg: "bg-blue-50/50",
    hover: "hover:border-blue-200",
    tag: "Recognition"
  },
  {
    icon: Bookmark,
    title: "BIS Recognized Laboratories",
    description: "The Bureau of Indian Standards (BIS) develops Indian product standards and recognizes laboratories for testing products against applicable BIS specifications.",
    whyRequired: "Testing confirms that products comply with applicable Indian Standards, supporting certification, quality assurance, and market acceptance.",
    color: "from-orange-400 to-[#F06C00]",
    bg: "bg-orange-50/50",
    hover: "hover:border-orange-200",
    tag: "Standards"
  },
  {
    icon: Activity,
    title: "APEDA Approved Laboratories",
    description: "The Agricultural and Processed Food Products Export Development Authority (APEDA) supports agricultural and processed food exports and recognizes laboratories for export-related testing.",
    whyRequired: "Many importing countries require export testing from recognized laboratories to verify compliance with residue limits, contaminants, and product specifications.",
    color: "from-rose-400 to-pink-500",
    bg: "bg-rose-50/50",
    hover: "hover:border-rose-200",
    tag: "Export"
  }
];

export function ConsultationServices() {
  return (
    <section className="max-w-7xl mx-auto px-6 py-24">
      <SectionHeader
        title={
          <>
            Certifications For{" "}
            <span className="text-gradient-brand">Every Dimension.</span>
          </>
        }
        subtitle="Our partner labs hold verified accreditations across NABL, FSSAI, BIS, APEDA, and more."
        badge="Global Standards"
        className="mb-10"
      />

      <div className="grid md:grid-cols-2 lg:grid-cols-2 gap-6">
         {services.map((service, idx) => (
           <div key={idx} className={cn(
             "group p-8 lg:p-10 rounded-[1.5rem] border border-slate-100 bg-white transition-all duration-700 shadow-[0_8px_30px_rgb(0,0,0,0.04)] hover:shadow-[0_20px_40px_rgb(0,0,0,0.08)] relative overflow-hidden flex flex-col justify-between",
             service.hover
           )}>
              {/* Subtle top-right gradient circle */}
              <div className={cn("absolute top-0 right-0 w-64 h-64 rounded-full translate-x-1/2 -translate-y-1/3 group-hover:scale-125 transition-transform duration-[2000ms] pointer-events-none", service.bg)} />
              
              <div className="relative z-10 space-y-6">
                <div className={cn(
                  "inline-flex h-14 w-14 items-center justify-center rounded-2xl shadow-md group-hover:scale-110 transition-transform duration-500 bg-gradient-to-br",
                  service.color
                )}>
                   <service.icon className="h-6 w-6 text-white" />
                </div>
                
                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <h3 className="text-lg font-bold text-slate-800 tracking-tight">{service.title}</h3>
                    <span className="text-[9px] font-black text-slate-300 uppercase tracking-[0.2em]">{service.tag}</span>
                  </div>
                  <div className="text-slate-500 text-sm leading-relaxed font-medium space-y-1">
                    <p>{service.description}</p>
                    <p>
                      <strong className="text-slate-700 mb-1">Why it is required?</strong><br />{service.whyRequired}
                    </p>
                  </div>
                </div>
                
              </div>

           </div>
         ))}
      </div>
    </section>
  );
}
